---
name: Thea
surname: Knowles
position: "Assistant Professor"
address: "University at Buffalo, Buffalo, NY"
phone: +1 716 370 6604
www: theaknowles.com
email: "theaknow@buffalo.edu"
twitter: theaknowles
github: thealk
linkedin: theaknowles
date: "`r Sys.Date()`"
#date: "`r format(Sys.time(), '%B %Y')`"
headcolor: "000000"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
knitr::opts_knit$set(root.dir = "../")
library(vitae)
library(readxl)
library(dplyr)
```

```{r}
message(getwd())
data <- readxl::read_xlsx("knowles_cv_data.xlsx")
```

<!-- # Some stuff about me -->

<!--  * I poisoned myself doing research. -->
<!--  * I was the first woman to win a Nobel prize -->
<!--  * I was the first person and only woman to win a Nobel prize in two different sciences. -->

# Current employment

```{r}
data %>% filter(section == "employment") %>%
  detailed_entries(with = institution, 
                   when = glue::glue(start," - ", end), 
                   what = title, 
                   where = loc)
```

# Education

```{r}
data %>% filter(section=="education") %>%
  detailed_entries(what = title,
                   when = end, 
                   with = institution, 
                   where = loc)
# tribble(
#   ~ Degree, ~ Year, ~ Institution, ~ Where,
#   "Informal studies", "1889-91", "Flying University", "Warsaw, Poland",
#   "Master of Physics", "1893", "Sorbonne Université", "Paris, France",
#   "Master of Mathematics", "1894", "Sorbonne Université", "Paris, France"
# ) %>% 
  # detailed_entries(Degree, Year, Institution, Where)
```

# Funding
## Research
```{r}
data %>% filter(section == "funding",
                subsection == "research") %>%
  detailed_entries(with = title, 
                   when = start,
                   what = details, 
                   where = loc )
```

## Clinical
```{r}
data %>% filter(section == "funding",
                subsection == "clinical") %>%
  detailed_entries(with = title, 
                   when = start, 
                   what = details, 
                   where = loc)
```

# Publications

```{r}
# knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("cv_data/thea.bib") %>%
  arrange(desc(issued))
```

# Presentations
```{r}
data %>% filter(section =="presentations") %>%
  detailed_entries(with = title, 
                   when = start, 
                   what = institution, 
                   where = loc,
                   why = details)
```

# Experience
## Research
```{r}
data %>% filter(section == "professional experience",
                subsection == "research") %>%
  detailed_entries(with = title,
                   what = institution,
                   when = paste(start,end,sep=" - "),
                   #when = glue::glue(start," - ",end),
                   where = loc,
                   why = details)
```

## Clinical
```{r}
data %>% filter(section == "professional experience",
                subsection == "clinical") %>%
  detailed_entries(with = title,
                   what = institution,
                   when = paste(start,end,sep=" - "),
                   #when = glue::glue(start," - ",end),
                   where = loc,
                   why = details)
```

# Professional development
```{r}
data %>% filter(section == "professional development") %>%
  detailed_entries(with = title,
                   what = institution,
                   when = paste(start, end, sep = " - "),
                   where = loc,
                   why = details)
```

# Professional affiliations
```{r}
data %>% filter(section == "professional affiliations") %>%
  detailed_entries(what = title,
                   with = institution,
                   when = paste(start, end, sep = " - "),
                   where = loc,
                   why = details)
```
